- hosts: workers
  remote_user: root
  vars:
    http_port: 80

  tasks:
    - name: install utils
      shell: apt install -y apache2-utils
    - name: copy lotus
      copy: src=/usr/local/bin/lotus dest=/usr/local/bin/lotus
    - name: copy lotus-miner
      copy: src=/usr/local/bin/lotus-storage-miner dest=/usr/local/bin/lotus-storage-miner
    - name: copy lotus-worker
      copy: src=/usr/local/bin/lotus-seal-worker dest=/usr/local/bin/lotus-seal-worker
    - name: copy run.sh
      copy: src=../run/run.sh dest=/root
    - name: run lotus worker
      shell: /root/run.sh worker_run
