- hosts: dminer
  remote_user: root
  vars:
    http_port: 80
  roles:
    - common

  tasks:
  - name: run lotus daemon
    shell: /root/run.sh daemon
  - name: run init lotus miner
    shell: /root/run.sh miner_init
  - name: run lotus miner
    shell: /root/run.sh miner_run